name: CI
on:
  - push
  - pull_request
permissions: {}
jobs:
  build:
    permissions:
      contents: read
    name: build-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-24.04'
            platform: 'linux-x64'
          - os: 'ubuntu-24.04'
            platform: 'win32-ia32'
          - os: 'ubuntu-24.04'
            platform: 'win32-x64'
          - os: 'ubuntu-24.04'
            platform: 'win32-arm64v8'
          - os: 'macos-15-intel'
            platform: 'darwin-x64'
          - os: 'macos-15'
            platform: 'darwin-arm64v8'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pipx install meson
          brew install automake nasm
      - name: Build ${{ matrix.platform }}
        run: ./build.sh ${{ matrix.platform }}
      - name: Upload ${{ matrix.platform }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: '*.tar.gz'
          compression-level: 0
          retention-days: 1
          if-no-files-found: error
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Create GitHub release for tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.tar.gz'
          artifactContentType: application/gzip
          prerelease: true
